version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    restart: always
    networks:
      - raga-net

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    restart: always
    depends_on:
      - backend
    networks:
      - raga-net

networks:
  raga-net:
    driver: bridge
