version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ragamatch-backend-prod
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    restart: unless-stopped
    environment:
      - BACKEND_HOST=${BACKEND_HOST:-0.0.0.0}
      - BACKEND_PORT=${BACKEND_PORT:-8000}
    volumes:
      - ./backend/model:/app/model:ro
    networks:
      - raga-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL:-http://localhost:8000}
    container_name: ragamatch-frontend-prod
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - raga-net
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

networks:
  raga-net:
    driver: bridge 